-- Table: flow_api_info
-- 接口配置类
CREATE TABLE IF NOT EXISTS `flow_api_info` (
  `id` bigint NOT NULL COMMENT '主键ID，通过Snowflake算法生成',
  `name` varchar(20) COMMENT 'API配置的名称',
  `directory_id` varchar(64) COMMENT '关联全局目录树',
  `url` varchar(100) COMMENT 'API的URL路径',
  `datasource` varchar(20) COMMENT '数据源名称',
  `module` varchar(20) COMMENT '所属模块名称',
  `method` varchar(10) COMMENT '请求方式：POST、PUT、GET、DELETE',
  `service_type` varchar(20) COMMENT '服务驱动类型：DB、FLOW、JSON、STRING',
  `response_type` varchar(10) COMMENT '响应数据类型：PAGE(分页)、LIST(列表)、OBJECT(对象)',
  `version` varchar(20) COMMENT 'API版本号',
  `config` longtext COMMENT '核心逻辑配置，存储SQL、流编排JSON或静态数据',
  `publish_status` smallint COMMENT '发布状态：0：未发布；1：已发布',
  `contract` mediumtext,
  `tags` varchar(500) COMMENT '标签，英文都好分隔',
  `level` int COMMENT '优先级，与请求的ss-level比较，大的优先',
  `template_id` varchar(32) COMMENT '基座模板ID',
  `custom_success_wrapper` text COMMENT '自定义成功返回包装',
  `custom_page_wrapper` text COMMENT '自定义分页返回包装',
  `custom_fail_wrapper` text COMMENT '自定义失败返回包装',
  `info` text COMMENT 'API配置的详细描述',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，自动记录为当前时间',
  `update_time` datetime COMMENT '更新时间',
  `deleted` int DEFAULT 0,
  `dsl_content` mediumtext COMMENT '逻辑编排 (FLOW) — Flow DSL JSON',
  `sql_content` text COMMENT '数据库 (DB) — SQL 脚本',
  `json_content` mediumtext COMMENT '静态 JSON (JSON) — JSON 内容',
  `text_content` text COMMENT '静态文本 (STRING) — 纯文本内容',
  `published_snapshot` mediumtext COMMENT '发布时的完整内容快照 (JSON)，运行时引擎从此字段读取',
  `publish_time` datetime COMMENT '最近一次发布时间',
  `log_enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否记录执行日志：1-开启，0-关闭',
  `cache_config` text COMMENT '响应缓存配置 JSON：enabled/ttlSeconds/keyParams/includePageable',
  `security_config` text COMMENT '入站防护 JSON：authMode/antiReplay/rateLimit/ipAllowlist',
  `view_export_config` text COMMENT '数据查看与导出 JSON：columns/sheetName/maxExportRows',
  PRIMARY KEY (`id`),
  KEY `idx_flow_api_info_directory_id` (`directory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='接口配置类';
