-- Table: flow_oss_object
-- OSS 文件台账（元数据在库，字节在 MinIO）
CREATE TABLE IF NOT EXISTS `flow_oss_object` (
  `id` varchar(32) NOT NULL COMMENT '雪花ID（隐私下载主键）',
  `profile_code` varchar(64) COMMENT '上传场景编码',
  `connection_code` varchar(64) COMMENT '连接编码',
  `bucket` varchar(128) COMMENT '桶名',
  `object_key` varchar(1024) COMMENT '对象键',
  `visibility` varchar(16) COMMENT 'PUBLIC / PRIVATE',
  `public_path` varchar(1024) COMMENT '公有相对路径',
  `original_name` varchar(512) COMMENT '原始文件名',
  `content_type` varchar(128) COMMENT 'Content-Type',
  `extension` varchar(32) COMMENT '扩展名',
  `size_bytes` bigint COMMENT '文件大小',
  `checksum_sha256` varchar(64) COMMENT 'SHA-256',
  `biz_meta` text COMMENT '业务扩展 JSON',
  `uploaded_by` varchar(64) COMMENT '上传人 userId',
  `uploaded_by_name` varchar(128) COMMENT '上传人展示名',
  `dept_id` varchar(64) COMMENT '部门 ID（数据权限）',
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE / DELETED',
  `expires_at` datetime DEFAULT NULL COMMENT '临时文件过期时间，空=不过期',
  `object_purged` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'MinIO 对象是否已物理删除：0=否, 1=是',
  `thumb_status` varchar(16) NOT NULL DEFAULT 'NONE' COMMENT 'NONE / PENDING / READY / FAILED / SKIPPED',
  `thumb_object_key` varchar(1024) DEFAULT NULL COMMENT '缩略图对象键',
  `thumb_public_path` varchar(1024) DEFAULT NULL COMMENT '缩略图公有路径',
  `thumb_content_type` varchar(128) DEFAULT NULL COMMENT '缩略图 Content-Type',
  `thumb_size_bytes` bigint DEFAULT NULL COMMENT '缩略图大小',
  `thumb_error` varchar(512) DEFAULT NULL COMMENT '缩略图失败原因',
  `create_time` datetime COMMENT '创建时间',
  `update_time` datetime COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_flow_oss_object_profile_code` (`profile_code`),
  KEY `idx_flow_oss_object_uploaded_by` (`uploaded_by`),
  KEY `idx_flow_oss_object_dept_id` (`dept_id`),
  KEY `idx_flow_oss_object_status` (`status`),
  KEY `idx_flow_oss_object_create_time` (`create_time`),
  KEY `idx_flow_oss_object_expires_at` (`expires_at`),
  KEY `idx_flow_oss_object_purge` (`status`, `object_purged`),
  KEY `idx_flow_oss_object_thumb_status` (`thumb_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OSS 文件台账';
